Feature/search page filters
gradiusalisik/aviasales-demo-frontend pull request #7
Opened 2018-03-09 06:45 UTC by gradiusalisik

2018-03-09 10:17 UTC, evgenyrodionov commented
Выбрал все — а "2 пересадки" не выбралось
![image](https://user-images.githubusercontent.com/775692/37202688-39dd3c08-239c-11e8-887d-9b2b4b3d2b64.png)

2018-03-09 10:18 UTC, evgenyrodionov commented
Данные не обновляются когда работаю со слайдером
![image](https://user-images.githubusercontent.com/775692/37202700-470d4954-239c-11e8-926b-e74de0599367.png)

2018-03-09 10:24 UTC, imevro requested changes
упрощай, оч сложно

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/AccordionCheckboxes.js
> +  return (
ставь переносы между блоками кода

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/AccordionCheckboxes.js
> +    : `${props.checkedIds.length} / ${props.list.length}`;
не очень понятно что тут происходит

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    this.state = {
частые ошибки второго эатпа читай

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +      this.state[checkedIds].push(id);
МУТАБЕЛЬНОСТЬ

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +  handleChangeFilter = checkedIds => id => ({ target }) => {
зачем тут каррирование?

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +      this.state[checkedIds].push(id);
спредом используй чтобы продублировать старый массив и добавить новое значение

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    const that = this;
это зачем? arrow функции имеют контекст родителя

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    const allCompany =
allCompany? Вся компания?

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +      list.duration.rightTime === this.state.duration.right;
ты не хочешь все эти проверки разруливать уже внутри компонентов? хз, дико выглядит

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +      list.duration.rightTime === this.state.duration.right;
передавать туда initialValue и в value текущий стейт

2018-03-09 10:24 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +            ['checkedIdsTransfer'],
почему два массива?

2018-03-10 13:14 UTC, evgenyrodionov commented
Вижу игнор замечания

2018-03-13 06:33 UTC, imevro requested changes

2018-03-13 06:33 UTC, evgenyrodionov commented on package.json
> +    "react-highlight-words": "^0.11.0",
0.11? Не самый лучший выбор, но ок

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Forms/index.js
> +    });
не понял эту проверку. Зачем так криво? приведи к одному виду

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Forms/index.js
> +    const paramsInputTo = this.state.to;
используй es destructing

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Forms/styled.js
> +    props.kind === 'simpleDate' &&
опять хуйня какая-то

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Forms/styled.js
> +    props.kind === 'simpleDate' &&
используй .extend и всё

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/AccordionCheckboxes.js
> +const quantityCheckedOptions = (isCheckedAll, checked, max) =>
если функция что-то возвращает, у неё префикс `get*`
функция по-умолчанию вообще глагол, `formatDate`, `getCheckedDates`

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +import initialState from './reset';
зачем?

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +import initialState from './reset';
ты сделал отдельный файл ради одного файла

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +} from './helpers/accordionsHelper';
избыточно как-то писать helper находясь в helpers

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    transfer: get(initialState, 'transfer', {}),
а это зачем? `transfer: initialState.transfer` чем не подошло? это раз

`state = initialState` тоже чем не подошло?

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    transfer: get(initialState, 'transfer', {}),
ну или спредом скопировать и добавить поля остальные

```
state = {
  ...initialState,
  x: 1
}
```

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +          checkedIds: state[name].checkedIds.concat(id),
опять мутабельность

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +  handleChangeFilter = name => id => ({ target }) => {
handleChangeFilter выглядит как функция для любого поля, а внутри речь про чекбоксы

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    this.setState(state => ({
ОТСТУПЫ
МЕЖДУ
БЛОКАМИ
КОДА

2018-03-13 06:33 UTC, evgenyrodionov commented on src/Search/Filter/Accordions.js
> +    args.map(name => this.setState({ [name]: defaultState[name] }));
во-первых, не map, а forEach

во-вторых, зачем кучу раз вызывать сетстейт, если можно один?

2018-03-13 11:26 UTC, gradiusalisik commented on src/Search/Filter/Accordions.js
> +          checkedIds: state[name].checkedIds.concat(id),
concat создаёт новый массив

2018-03-13 13:15 UTC, gradiusalisik commented on src/Forms/index.js
> +    });
проверку убрал, вероятно комментарий остался потому что код с value остался
http://prntscr.com/iqlilh

2018-05-05 09:33 UTC, merged